#!/usr/bin/env bash

# Help
###########################

gkb_extensions_help() {
	echo "GraphKB CLI v$GKB_VERSION
Extensions command help

Command: extensions

Usage: $GKB_NAME_TO_PATH extensions [help] <service> <id>

Help:
	-h, --help  Get help on the extensions command

Services:
	C, clinicaltrialsgov <id>  Given a trial id, query the clinicaltrials.gov API
	                           e.g. \$ $GKB_NAME_TO_PATH extensions clinicaltrialsgov NCT03478891
	                                \$ $GKB_NAME_TO_PATH e C NCT03478891

	G, gene <id>               Given a gene id, query the Gene database of the NCBI's Entrez API
	                           e.g. \$ $GKB_NAME_TO_PATH extensions gene 1956
	                                \$ $GKB_NAME_TO_PATH e G 1956

	P, pubmed <id>             Given a Pubmed id, query the Pubmed database of the NCBI's Entrez API
	                           e.g. \$ $GKB_NAME_TO_PATH extensions pubmed 28244479
	                                \$ $GKB_NAME_TO_PATH e P 28244479
	"
	exit $1
}


# Query
###########################

gkb_extensions()
{

	case $1 in
		'C'|'clinicaltrialsgov')
			service='clinicaltrialsgov'
		;;
		'G'|'gene')
			service='gene'
		;;
		'P'|'pubmed')
			service='pubmed'
		;;
		*)
			echo "$1 is not a supported service."
			gkb_extensions_help 1
		;;
	esac

	printf -v headerAuth 'Authorization: %s' $GKB_TOKEN
	echo $(curl \
        -X GET \
        -H "Content-Type: application/json" \
		-H "$headerAuth" \
        --silent \
		$GKB_BASE_URL/extensions/$service/$2
    )
}


# Command Entry Point
###########################

# Help
if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
	gkb_extensions_help 0
elif [[ ${1:0:1} == "-" ]]; then
	echo "$1 cannot be processed. Is it an option needing to come before the command?"
	gkb_extensions_help 1
fi


# Run command
if [[ $2 != '' ]]; then
	gkb_extensions $@
else
	gkb_extensions_help 1
fi
