#!/usr/bin/env bash

# Help
###########################

gkb_stats_help() {
	echo "
Command: stats
Usage: gkb stats [help|options] [classes]

Help:
	-e, --examples  ...
	-h, --help      Get help on the stats command

Options:
	-g, --groupBy <value> A column name to group counts on.
	                      One of [relevance|subject|conditions|evidence|source|
	                      evidenceLevel|type|reference1|reference2]
	-H, --history         Include soft-deleted records
	"
	exit $1
}

gkb_stats_examples() {
	echo "GraphKB CLI v$GKB_VERSION
Stats command examples

Record counts:

	# If classes arg is ommited, all classes but those abstract,
	# embeeded or non-terminal (w/ subclasses) get compiled
	  $ $GKB_NAME_TO_PATH stats

	# The list of classes to compile seperate counts for must be
	# seperated by a comma, without space.
	  $ $GKB_NAME_TO_PATH stats Statement
	  $ $GKB_NAME_TO_PATH stats Statement,PositionalVariant,Therapy

	# Get soft-deleted records accounted for with the --history flag
	  $ $GKB_NAME_TO_PATH stats --history Statement

Grouping:

	# Chose one grouping field among: relevance, subject, conditions, evidence, source,
	# evidenceLevel, type, reference1 & reference2.
	  $ $GKB_NAME_TO_PATH stats --groupBy source Therapy
	  $ $GKB_NAME_TO_PATH stats --groupBy relevance Statement
	  $ $GKB_NAME_TO_PATH stats --groupBy type PositionalVariant

	"
	exit 0
}

# Globals
###############################

classList=''
groupBy=''
history=false


# Options
###############################
# 0: key option
# 1: key-value option
# 2: return help

gkb_stats_options()
{
	case $1 in
		'-g'|'--groupBy')
			if [[ $2 != '' ]]; then
				echo "1 groupBy=$2"
			else
				echo "2 $1"
			fi
		;;
		'-H'|'--history')
			echo "0 history=true"
		;;
		*)
			echo "2 $1"
		;;
	esac
}


# Stats
###########################

gkb_stats()
{
	if [[ $1 != '' ]]; then
		printf -v classList 'classList=%s' $1
	else
		printf -v classList ''
	fi

	if [[ $groupBy != '' ]]; then
		printf -v groupBy 'groupBy=%s' $groupBy
	else
		printf -v groupBy ''
	fi

	printf -v history 'history=%s' $history
	printf -v headerAuth 'Authorization: %s' $GKB_TOKEN

	echo $(curl \
        -G \
        -H "Content-Type: application/json" \
		-H "$headerAuth" \
		-d "$classList" \
		-d "$groupBy" \
		-d "$history" \
        --silent \
		$GKB_BASE_URL/stats
    )
}


# Command Entry Point
###########################

# Extract options
pos=1
options=()
for (( i=1; i <= "$#"; i++ )); do
    if [[ ${!i:0:1} == "-" ]]; then

        # Extract option
        nextArg=$(($i+1))
        IFS=' ' read -r -a option <<< $(gkb_stats_options ${!i} ${!nextArg})

		if [[ ${option[0]} == "0" ]]; then
			options+=(${option[1]})
		elif [[ ${option[0]} == "1" ]]; then
			options+=(${option[1]})
			# Skip next argument since option is paired with a value
			i=$(($i+1))
		else
			case ${option[1]} in
				'-e'|'--examples')
					gkb_stats_examples
				;;
				'-h'|'--help')
					gkb_stats_help 0
				;;
				*)
					echo "${option[1]} cannot be processed. Is the option valid or needs to be paired with one or more value(s)?"
					gkb_stats_help 1
				;;
			esac
		fi

    else
        pos=$i
        break
    fi
    pos=$i
done

# Set option variables
for (( i=0; i < ${#options[@]}; i++ )); do
	# Carefull use of dynamic eval!
	eval ${options[i]}
done

# Run command
gkb_stats ${@:pos}
