#!/usr/bin/env bash


# Help
###########################

gkb_version_help() {
	echo "
Command: version
Usage: gkb version
	"
	exit 1
}


# Version
###########################

gkb_version()
{
	echo $(curl \
        -X GET \
        --header "Content-Type: application/json" \
        --silent \
		$GKB_BASE_URL/version
    )
}


# Command Entry Point
###########################
gkb_version
